package org.omegat.core.team2.encryption;

import java.security.MessageDigest;
import java.security.SecureRandom;
import java.util.Arrays;
import java.util.logging.Logger;

import javax.crypto.Cipher;
import javax.crypto.spec.GCMParameterSpec;
import javax.crypto.spec.SecretKeySpec;

import org.omegat.util.Log;

/**
 * Handles AES-256/GCM encryption and decryption of repositories.properties
 * content. The key is derived on-the-fly from the machine+user ID generated by
 * MachineIdGenerator and is never stored on disk.
 *
 * File format on disk:
 *   [ 4 bytes magic ][ 12 bytes IV ][ N bytes AES-GCM ciphertext + 16-byte auth tag ]
 *
 * The magic header allows TeamSettings to reliably distinguish encrypted files
 * from plain-text ones without relying on length heuristics or silent failures.
 *
 * Migration: if the magic header is absent the caller treats the file as
 * plain-text, loads it, and re-saves it through the encrypted path.
 */
public final class TeamSettingsEncryptor {

    private static final Logger LOGGER = Logger.getLogger(TeamSettingsEncryptor.class.getName());

    private static final String CIPHER_ALGO  = "AES/GCM/NoPadding";
    private static final int    GCM_TAG_BITS = 128;
    private static final int    IV_LENGTH    = 12;

    // 4-byte magic marker prepended to every encrypted file.
    // Chosen to be invalid UTF-8 so it can never appear in a plain-text
    // Java properties file.
    private static final byte[] MAGIC = { (byte) 0xC5, (byte) 0x75, (byte) 0xE5, (byte) 0x01 };

    private TeamSettingsEncryptor() {
    }

    private static SecretKeySpec deriveKey() throws Exception {
        String machineId = MachineIdGenerator.getMachineId();
        MessageDigest sha = MessageDigest.getInstance("SHA-256");
        byte[] keyBytes = sha.digest(machineId.getBytes("UTF-8"));
        return new SecretKeySpec(keyBytes, "AES");
    }

    /**
     * Returns true if {@code data} starts with the encrypted-file magic header.
     * Use this to cheaply distinguish encrypted files from plain-text ones
     * before calling {@link #decrypt(byte[])}.
     */
    public static boolean isEncrypted(byte[] data) {
        if (data.length < MAGIC.length) {
            return false;
        }
        for (int i = 0; i < MAGIC.length; i++) {
            if (data[i] != MAGIC[i]) {
                return false;
            }
        }
        return true;
    }

    /**
     * Encrypts raw bytes (the plain-text properties content).
     * A fresh random IV is generated for every call and prepended to the output
     * after the magic header.
     *
     * Layout: MAGIC(4) + IV(12) + ciphertext
     *
     * @param plainText the plain-text content to encrypt
     * @return magic + IV + ciphertext as a single byte array
     */
    public static byte[] encrypt(byte[] plainText) throws Exception {
        byte[] iv = new byte[IV_LENGTH];
        new SecureRandom().nextBytes(iv);

        Cipher cipher = Cipher.getInstance(CIPHER_ALGO);
        cipher.init(Cipher.ENCRYPT_MODE, deriveKey(), new GCMParameterSpec(GCM_TAG_BITS, iv));
        byte[] cipherText = cipher.doFinal(plainText);

        byte[] out = new byte[MAGIC.length + IV_LENGTH + cipherText.length];
        System.arraycopy(MAGIC,      0, out, 0,                         MAGIC.length);
        System.arraycopy(iv,         0, out, MAGIC.length,              IV_LENGTH);
        System.arraycopy(cipherText, 0, out, MAGIC.length + IV_LENGTH,  cipherText.length);
        return out;
    }

    /**
     * Decrypts a byte array produced by {@link #encrypt(byte[])}.
     * Throws {@link IllegalArgumentException} if the magic header is absent
     * (i.e. the file is plain-text, not encrypted).
     * Throws other exceptions if the data has been tampered with or was not
     * encrypted with this machine's key (GCM authentication failure).
     *
     * @param encryptedData magic + IV + ciphertext
     * @return original plain-text bytes
     */
    public static byte[] decrypt(byte[] encryptedData) throws Exception {
        if (!isEncrypted(encryptedData)) {
            throw new IllegalArgumentException(
                    "Missing magic header - file is not encrypted by TeamSettingsEncryptor");
        }
        if (encryptedData.length <= MAGIC.length + IV_LENGTH) {
            throw new IllegalArgumentException("Data too short to contain IV and ciphertext");
        }

        byte[] iv = new byte[IV_LENGTH];
        System.arraycopy(encryptedData, MAGIC.length, iv, 0, IV_LENGTH);

        Cipher cipher = Cipher.getInstance(CIPHER_ALGO);
        cipher.init(Cipher.DECRYPT_MODE, deriveKey(), new GCMParameterSpec(GCM_TAG_BITS, iv));
        return cipher.doFinal(encryptedData, MAGIC.length + IV_LENGTH,
                encryptedData.length - MAGIC.length - IV_LENGTH);
    }
}