/**************************************************************************
 OmegaT - Computer Assisted Translation (CAT) tool
          with fuzzy matching, translation memory, keyword search,
          glossaries, and translation leveraging into updated projects.

 Copyright (C) 2024 Thomas CORDONNIER
               Home page: http://www.omegat.org/
               Support center: https://omegat.org/support

 This file is part of OmegaT.

 OmegaT is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 OmegaT is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **************************************************************************/

package org.omegat.gui.preferences.view;

import javax.swing.JPanel;

import org.omegat.util.OStrings;

/**
 * @author Aaron Madlon-Kay
 */
@SuppressWarnings("serial")
public class PropagationOptionsPanel extends JPanel {

    /** Creates new form PropagationOptionsPanel */
    public PropagationOptionsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayMultipleMatchesCheckBox = new javax.swing.JCheckBox();
        autoDisabledOnlyCheckBox = new javax.swing.JCheckBox();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setMinimumSize(new java.awt.Dimension(250, 200));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        org.openide.awt.Mnemonics.setLocalizedText(displayMultipleMatchesCheckBox, OStrings.getString("PREFS_PROPAGATION_VIEW_MATCHES")); // NOI18N
        add(displayMultipleMatchesCheckBox);

        org.openide.awt.Mnemonics.setLocalizedText(autoDisabledOnlyCheckBox, OStrings.getString("PREFS_PROPAGATION_AUTO_ONLY")); // NOI18N
        autoDisabledOnlyCheckBox.setMargin(new java.awt.Insets(2, 20, 2, 2));
        add(autoDisabledOnlyCheckBox);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JCheckBox autoDisabledOnlyCheckBox;
    javax.swing.JCheckBox displayMultipleMatchesCheckBox;
    // End of variables declaration//GEN-END:variables
}
