/**************************************************************************
 OmegaT - Computer Assisted Translation (CAT) tool 
          with fuzzy matching, translation memory, keyword search, 
          glossaries, and translation leveraging into updated projects.

 Copyright (C) 2024 Thomas Cordonnier
               Home page: http://www.omegat.org/
               Support center: http://groups.yahoo.com/group/OmegaT/

 This program is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 2 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software
 Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA
 **************************************************************************/

package org.omegat.gui.multtrans;

import java.awt.Frame;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;

import java.io.*;
import java.nio.file.*;
import java.util.List;

import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.Box;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.KeyStroke;

import org.omegat.core.Core;
import org.omegat.core.data.TMXEntry;
import org.omegat.core.data.PrepareTMXEntry;
import org.omegat.core.data.SourceTextEntry;
import org.omegat.util.OStrings;
import org.omegat.util.Preferences;

/**
 * 
 * @author Thomas Cordonnier
 */
@SuppressWarnings("serial")
public class PropagateOptionsDialog extends JDialog {
    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;

    /** Creates new form WorkflowOptionsDialog */
    public PropagateOptionsDialog(Frame parent) {
        super(parent, true);

        // HP
        // Handle escape key to close the window
        KeyStroke escape = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0, false);
        Action escapeAction = new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        };
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(escape, "ESCAPE");
        getRootPane().getActionMap().put("ESCAPE", escapeAction);
        // END HP

        initComponents();
        loadPreferences();

        getRootPane().setDefaultButton(okButton);

        // initializing options
        
        invalidate();
        pack(); setResizable(false);
    }

    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();        
        onlyUntranslated = new javax.swing.JCheckBox();
        org.openide.awt.Mnemonics.setLocalizedText(onlyUntranslated, OStrings.getString("PROPAGATE_WINDOW_OPT_UNTRA"));
        rBack = new javax.swing.JRadioButton();
        org.openide.awt.Mnemonics.setLocalizedText(rBack, OStrings.getString("PROPAGATE_WINDOW_OPT_BACK"));
        rFront = new javax.swing.JRadioButton();
        org.openide.awt.Mnemonics.setLocalizedText(rFront, OStrings.getString("PROPAGATE_WINDOW_OPT_FWD"));
        rBoth = new javax.swing.JRadioButton();
        org.openide.awt.Mnemonics.setLocalizedText(rBoth, OStrings.getString("PROPAGATE_WINDOW_OPT_BOTH"));

        setTitle(OStrings.getString("MULT_MENU_PROPAGATE")); 
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new BorderLayout());

        Box buttonsBox = Box.createHorizontalBox();
        this.add (buttonsBox, BorderLayout.SOUTH);
        
        Box bOptions = Box.createVerticalBox();
        this.add(bOptions, BorderLayout.NORTH);
        
        Box bDirections = Box.createHorizontalBox();
        bDirections.add(rBack); bDirections.add(rFront); bDirections.add(rBoth);
        javax.swing.ButtonGroup dirGroup = new javax.swing.ButtonGroup();
        dirGroup.add(rBack); dirGroup.add(rFront); dirGroup.add(rBoth);
        rBoth.setSelected(true);
                
        bOptions.add(bDirections, BorderLayout.NORTH);
        bOptions.add(onlyUntranslated, BorderLayout.SOUTH);
                
        org.openide.awt.Mnemonics.setLocalizedText(okButton, OStrings.getString("BUTTON_OK")); // NOI18N
        okButton.addActionListener(this::okButtonActionPerformed);
        javax.swing.JPanel pButtons = new javax.swing.JPanel();
        this.add (pButtons, BorderLayout.SOUTH); 
        pButtons.add (buttonsBox, BorderLayout.EAST);        
        buttonsBox.add(okButton);

        org.openide.awt.Mnemonics.setLocalizedText(cancelButton, OStrings.getString("BUTTON_CANCEL")); // NOI18N
        cancelButton.addActionListener(this::cancelButtonActionPerformed);
        buttonsBox.add(cancelButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void loadPreferences() {
        onlyUntranslated.setSelected(Preferences.isPreference(Preferences.PROPAGATION_SELECT_TRA_ONLY));
        String direction = Preferences.getPreferenceDefault(Preferences.PROPAGATION_SELECT_DIR, "both");
        rBoth.setSelected("both".equals(direction));
        rBack.setSelected("back".equals(direction));
        rFront.setSelected("front".equals(direction));
    }

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt)// GEN-FIRST:event_okButtonActionPerformed
    {
        Preferences.setPreference(Preferences.PROPAGATION_SELECT_TRA_ONLY, onlyUntranslated.isSelected());
        if (rBoth.isSelected()) {
            Preferences.setPreference(Preferences.PROPAGATION_SELECT_DIR,"both");
        } else if (rBack.isSelected()) {
            Preferences.setPreference(Preferences.PROPAGATION_SELECT_DIR,"back");
        } else if (rFront.isSelected()) {
            Preferences.setPreference(Preferences.PROPAGATION_SELECT_DIR,"front");
        }
    
        final SourceTextEntry ste = Core.getEditor().getCurrentEntry();
        final TMXEntry curTra = Core.getProject().getTranslationInfo(ste);
        List<SourceTextEntry> dups = ste.getDuplicates();
        if (dups == null) {
            return;
        }
        PrepareTMXEntry p = new PrepareTMXEntry(curTra);
        int i = 0;
        for (SourceTextEntry dup: dups) {
            if (rBack.isSelected()) {
                if (dup.entryNum() > ste.entryNum()) {
                    continue;
                }
            }
            if (rFront.isSelected()) {
                if (dup.entryNum() < ste.entryNum()) {
                    continue;
                }
            }
            if (onlyUntranslated.isSelected()) {
                TMXEntry tmx2 = Core.getProject().getTranslationInfo(dup);
                if (tmx2.isTranslated() && (! tmx2.defaultTranslation)) {
                    continue;
                }
            }
            Core.getProject().setTranslation(dup, p, false, curTra.linked);
            i = i + 1;
        }
        doClose(RET_OK);
        javax.swing.JOptionPane.showMessageDialog(null, 
            OStrings.getString("MULT_MENU_PROPAGATE_RES").replace("{0}", Integer.toString(i)), 
            OStrings.getString("MULT_MENU_PROPAGATE"), javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }// GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt)// GEN-FIRST:event_cancelButtonActionPerformed
    {
        doClose(RET_CANCEL);
    }// GEN-LAST:event_cancelButtonActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt)// GEN-FIRST:event_closeDialog
    {
        doClose(RET_CANCEL);
    }// GEN-LAST:event_closeDialog

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton okButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JRadioButton rBack, rFront, rBoth;
    private javax.swing.JCheckBox onlyUntranslated;    
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
