/**************************************************************************
 OmegaT - Computer Assisted Translation (CAT) tool
          with fuzzy matching, translation memory, keyword search,
          glossaries, and translation leveraging into updated projects.

 Copyright (C) 2024 Thomas CORDONNIER
               Home page: http://www.omegat.org/
               Support center: https://omegat.org/support

 This file is part of OmegaT.

 OmegaT is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 OmegaT is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **************************************************************************/

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.omegat.gui.multtrans;

import org.omegat.util.OStrings;
import org.omegat.util.gui.StaticUIUtils;

/**
 *
 * @author Thomas Cordonnier
 */
@SuppressWarnings("serial")
public class PropagateSearchWindowForm extends javax.swing.JFrame {

    /**
     * Creates new form PropagateSearchWindowForm
     */
    public PropagateSearchWindowForm() {
        StaticUIUtils.setWindowIcon(this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroupDirection = new javax.swing.ButtonGroup();
        m_panelSearch = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        rbBack = new javax.swing.JRadioButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        rbFront = new javax.swing.JRadioButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        rbBoth = new javax.swing.JRadioButton();
        filler14 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        m_resultsLabel = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        panelLine2 = new javax.swing.JPanel();
        cb_OnlyUntranslated = new javax.swing.JCheckBox();
        filler29 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        filler17 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        filler24 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        m_searchButton = new javax.swing.JButton();
        filler23 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jScrollPane1 = new javax.swing.JScrollPane();
        m_viewer = new PropagateEntryListPane();
        jPanel8 = new javax.swing.JPanel();
        filler13 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jPanel7 = new javax.swing.JPanel();
        m_autoSyncWithEditor = new javax.swing.JCheckBox();
        m_backToInitialSegment = new javax.swing.JCheckBox();
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        m_propagateAllButton = new javax.swing.JButton();
        filler18 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        filler16 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        m_filterButton = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        m_dismissButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        m_panelSearch.setLayout(new java.awt.GridLayout(3, 0));

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        buttonGroupDirection.add(rbBack);
        rbBack.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(rbBack, OStrings.getString("PROPAGATE_WINDOW_OPT_BACK")); // NOI18N
        jPanel2.add(rbBack);
        jPanel2.add(filler3);

        buttonGroupDirection.add(rbFront);
        org.openide.awt.Mnemonics.setLocalizedText(rbFront, OStrings.getString("PROPAGATE_WINDOW_OPT_FWD")); // NOI18N
        jPanel2.add(rbFront);
        jPanel2.add(filler4);

        buttonGroupDirection.add(rbBoth);
        org.openide.awt.Mnemonics.setLocalizedText(rbBoth, OStrings.getString("PROPAGATE_WINDOW_OPT_BOTH")); // NOI18N
        jPanel2.add(rbBoth);
        jPanel2.add(filler14);
        jPanel2.add(m_resultsLabel);
        jPanel2.add(filler2);

        m_panelSearch.add(jPanel2);

        panelLine2.setLayout(new javax.swing.BoxLayout(panelLine2, javax.swing.BoxLayout.LINE_AXIS));

        cb_OnlyUntranslated.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(cb_OnlyUntranslated, OStrings.getString("PROPAGATE_WINDOW_OPT_UNTRA")); // NOI18N
        panelLine2.add(cb_OnlyUntranslated);
        panelLine2.add(filler29);
        panelLine2.add(filler5);
        panelLine2.add(filler17);
        panelLine2.add(filler6);
        panelLine2.add(filler24);

        org.openide.awt.Mnemonics.setLocalizedText(m_searchButton, OStrings.getString("BUTTON_SEARCH")); // NOI18N
        panelLine2.add(m_searchButton);
        panelLine2.add(filler23);

        m_panelSearch.add(panelLine2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        getContentPane().add(m_panelSearch, gridBagConstraints);

        m_viewer.setText(OStrings.getString("SW_VIEWER_TEXT")); // NOI18N
        jScrollPane1.setViewportView(m_viewer);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.LINE_AXIS));
        jPanel8.add(filler13);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        getContentPane().add(jPanel8, gridBagConstraints);

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        org.openide.awt.Mnemonics.setLocalizedText(m_autoSyncWithEditor, OStrings.getString("SW_AUTO_SYNC")); // NOI18N
        m_autoSyncWithEditor.setFocusable(false);
        m_autoSyncWithEditor.setMinimumSize(new java.awt.Dimension(105, 21));
        jPanel7.add(m_autoSyncWithEditor);

        org.openide.awt.Mnemonics.setLocalizedText(m_backToInitialSegment, OStrings.getString("SW_BACK_TO_INITIAL_SEGMENT")); // NOI18N
        m_backToInitialSegment.setFocusable(false);
        m_backToInitialSegment.setMinimumSize(new java.awt.Dimension(105, 21));
        jPanel7.add(m_backToInitialSegment);
        jPanel7.add(filler12);

        org.openide.awt.Mnemonics.setLocalizedText(m_propagateAllButton, OStrings.getString("PROPAGATE_WINDOW_BTN_ALL")); // NOI18N
        jPanel7.add(m_propagateAllButton);
        jPanel7.add(filler18);
        jPanel7.add(filler16);

        org.openide.awt.Mnemonics.setLocalizedText(m_filterButton, OStrings.getString("BUTTON_FILTER")); // NOI18N
        m_filterButton.setEnabled(false);
        jPanel7.add(m_filterButton);
        jPanel7.add(filler1);

        org.openide.awt.Mnemonics.setLocalizedText(m_dismissButton, OStrings.getString("BUTTON_CLOSE")); // NOI18N
        jPanel7.add(m_dismissButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        getContentPane().add(jPanel7, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.ButtonGroup buttonGroupDirection;
    javax.swing.JCheckBox cb_OnlyUntranslated;
    javax.swing.Box.Filler filler1;
    javax.swing.Box.Filler filler12;
    javax.swing.Box.Filler filler13;
    javax.swing.Box.Filler filler14;
    javax.swing.Box.Filler filler16;
    javax.swing.Box.Filler filler17;
    javax.swing.Box.Filler filler18;
    javax.swing.Box.Filler filler2;
    javax.swing.Box.Filler filler23;
    javax.swing.Box.Filler filler24;
    javax.swing.Box.Filler filler29;
    javax.swing.Box.Filler filler3;
    javax.swing.Box.Filler filler4;
    javax.swing.Box.Filler filler5;
    javax.swing.Box.Filler filler6;
    javax.swing.JPanel jPanel2;
    javax.swing.JPanel jPanel7;
    javax.swing.JPanel jPanel8;
    javax.swing.JScrollPane jScrollPane1;
    javax.swing.JCheckBox m_autoSyncWithEditor;
    javax.swing.JCheckBox m_backToInitialSegment;
    javax.swing.JButton m_dismissButton;
    javax.swing.JButton m_filterButton;
    javax.swing.JPanel m_panelSearch;
    javax.swing.JButton m_propagateAllButton;
    javax.swing.JLabel m_resultsLabel;
    javax.swing.JButton m_searchButton;
    javax.swing.JTextPane m_viewer;
    javax.swing.JPanel panelLine2;
    javax.swing.JRadioButton rbBack;
    javax.swing.JRadioButton rbBoth;
    javax.swing.JRadioButton rbFront;
    // End of variables declaration//GEN-END:variables
}
